services:
    neo4j-metagraph:
        image: neo4j:5.12.0
        hostname: neo4j
        container_name: metagraph-neo4j
        ports: 
        - 7474:7474
        - 7687:7687
        environment:
        - NEO4J_AUTH=none
        volumes:
        - ./rework/out:/root/out:ro

    metagraph:
        build: .
        env_file: ./rework/.env
        volumes:
            - ./main.py:/app/main.py
            - ./rework:/app/rework
